language: cpp

sudo: required

services:
  - docker

stages:
  - build
  - deploy

# Display information before we start the build.
before_script:
  - docker info
  - apk add --update curl jq && rm -rf /var/cache/apk/*
  - apk update && apk add git
  - apk add --update --no-cache bash openssl ca-certificates unzip
  - apk add --update docker-compose
  - apk update && apk upgrade
  - git clone https://github.com/chalmers-revere/opendlv-video-h264-decoder.git
  - docker-compose --version
  - ls

# This section describes what shall be done to build and test the project.
build-and-test:
  only:
    - branches
  tags:
    - docker-build
  stage: build
  script:
    - docker build -t group4:latest -f Dockerfile .
    - docker create --cidfile "cid.txt" group4:latest
    - docker cp `cat cid.txt`:/opt/report.pdf .
    - docker rm `cat cid.txt`
 addons:
  artifacts: true
        paths:
          - report.pdf
