version: '3'
#sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#https://stackoverflow.com/questions/66579446/error-executing-docker-compose-building-webserver-unable-to-prepare-context-un
services:
  open-dlv:
    container_name: opendlv-vehicle-view
    image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
    restart: on-failure
    network_mode: "host"
    volumes:
      - $PWD/recordings:/opt/vehicle-view/recordings
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8081"
  h264:
    build:
      context: ./opendlv-video-h264-decoder/
      dockerfile: Dockerfile.amd64
    restart: on-failure
    depends_on:
      - open-dlv
    network_mode: "host"
    container_name: h264
    ipc: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp:/tmp
    command: "--cid=253 --name=img"
  selenium:
    build: ./performance_testing/
    volumes:
      - $PWD/recordings:/recordings
      - /var/run/docker.sock:/var/run/docker.sock
      - /csv_files:/csv_files
      - /builds/courses/dit638/students/2021-group-04/graphs:/graphs
      - /builds/courses/dit638/students/2021-group-04/steering_CSV:/steering_CSV
    container_name: selenium
    depends_on:
      - h264
    network_mode: "host"
    ipc: "host"